name: CI/CD
on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
    unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                lfs: true
          - name: GdUnit4 Tests
            uses: MikeSchulze/gdUnit4-action@v1
            with:
                godot-version: '4.3'	  
                paths: 'res://test' 
