name: CI/CD

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
    unit-tests:
        name: Run Unit Tests
        runs-on: ubuntu-latest
        steps:
	  # 1. Check out your repository code
          - name: Checkout Code
            uses: actions/checkout@v4
            with:
                lfs: true  # Enable LFS if you use it for large assets (images/audio)
          - name: GdUnit4 Tests
            uses: MikeSchulze/gdUnit4-action@v1
            with:
		  # CHANGE THIS to match your local Godot version (e.g. 4.2, 4.3)
                godot-version: '4.3'	  
                paths: 'res://test' 
